modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "playerwizard"
version = "${version}"
displayName = "PlayerWizard"
authors = "AlgorithmLX"
description = '''
Easy Head utility
'''
logoFile = "logo.png"

[[dependencies.playerwizard]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerwizard]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"