modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="MIT"
#issueTrackerURL=""

[[mods]]
modId="playerwizard"
version="${version}"
displayName="PlayerWizard"
logoFile="logo.png"
authors="AlgorithmLX" #optional
description='''Easy Head utility'''

[[mixins]]
config="playerwizard.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.playerwizard]]
modId="neoforge"
type="required"
versionRange="[20.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.playerwizard]]
modId="minecraft"
type="required"
versionRange="[1.20.6,)"
ordering="NONE"
side="BOTH"
